name: 01 - Build
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      sha: ${{ steps.version.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version & SHA
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=dist-${{ steps.version.outputs.version }}-${{ steps.version.outputs.sha }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build script & create dist package
        run: |
          npm run build
          npm run create-dist-package

      - name: Install zip tool
        run: sudo apt-get update -q && sudo apt-get install -y zip

      - name: Create ZIP
        run: zip -r $ARTIFACT_NAME.zip dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: $ARTIFACT_NAME.zip
          retention-days: 7