name: 02 - Deploy
on:
  workflow_run:
    workflows: ["01 - Build"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Download release asset using GitHub CLI
        run: |
          gh release download ${{ github.ref_name }} --repo ${{ github.repository }} --pattern standalone-dist.zip
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Unzip
        run: unzip standalone-dist.zip

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Artifact to EC2
        run: scp -r dist ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/app
          rm -rf dist
          mv dist dist
          pm2 delete next-app || true
          pm2 start npm --name "next-app" -- start
          pm2 save
          EOF
