name: 02 - Deploy
on:
  workflow_run:
    workflows: ["01 - Build"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=standalone-dist" >> $GITHUB_ENV

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          run-id: ${{ github.event.workflow_run.id }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Artifact to EC2
        run: scp -r ${{ env.ARTIFACT_NAME }} ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/app
          rm -rf dist
          mv ${{ env.ARTIFACT_NAME }} dist
          pm2 delete next-app || true
          pm2 start npm --name "next-app" -- start
          pm2 save
          EOF
